name: CI/CD with PostgreSQL

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: ${{ secrets.DB_NAME }}
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASS }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U ${{ secrets.DB_USER }} -d ${{ secrets.DB_NAME }}"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASS }}
      DB_HOST: localhost

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install PostgreSQL Client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Verify Database Connection
        run: |
          export PGPASSWORD=$DB_PASS
          psql -h $DB_HOST -U $DB_USER -d $DB_NAME -c "SELECT NOW();"

      - name: Insert Test Data
        run: bash scripts/ingest.sh

      - name: Fetch Data to Verify
        run: |
          export PGPASSWORD=$DB_PASS
          psql -h $DB_HOST -U $DB_USER -d $DB_NAME -c "SELECT * FROM users;"    

      - name: Run Database Backup
        run: bash scripts/backup.sh

      - name: Verify Backup File
        run: ls -lah backup.sql || echo "backup.sql not found!"

      - name: Upload Database Backup
        uses: actions/upload-artifact@v4
        with:
          name: db-backup
          path: backup.sql

      - name: Run Database Migration
        run: bash scripts/migrate.sh

      - name: Rollback on Failure
        if: failure()
        run: bash scripts/rollback.sh
